### ISSUE TITLE
Fluire. Плейлист. Поле редактирования описания плейлиста нелогично работает.

### ISSUE THREAD

**Issue by GodofRussia** [VK-BMSTU-QA/homework-1-autumn-2023#44]
Приоритет:  низкий

<img width="1744" alt="image" src="https://github.com/yarikTri/homework-1-autumn-2023/assets/82154423/b9b3414c-3e48-4206-b1cc-5f934886db50">

URL: http://84.23.54.19/playlist/256 (id вашего личного плейлиста)

Сценарий воспроизведения:
1) Открыть страницу личного плейлиста
2) Нажать на название или описание (если есть) плейлиста
3) Нажать в любую область поля в форме

Ожидаемый результат: В описании нажатие в любую область placeholder'а переводит курсор в начало строки
Фактический результат: при нажатии в любую область placeholder'а в поле описания, курсор остаётся там, где и было нажатие. Всё символьное пространство до курсора заполняется пробелами.

**Comment by yarikTri** [comment]
А есть же уже issue, который описывает по сути этот же баг

**Comment by GodofRussia** [comment]
удалить этот? дублирует другой

**Comment by yarikTri** [comment]
Ага

**Comment by yarikTri** [comment]
Аппрув закрытия)
